# Changes here will be overwritten by Copier
_commit: v0.14.1
_src_path: gh:bhklab/bhklab-project-template
author_email: julianguyen.bhklab@gmail.com
author_full_name: Julia Nguyen
github_username: julianguyn
has_additional_authors: false
project_description: Score ARCHE signature expression from input narrowPeak files
project_name: BCa_ARCHE_Scoring
project_slug: bca_arche_scoring
publish_to_github: true
python_version: '3.12'
repo_location: julianguyn
