opname: "cfDNA_ATAC"
metadatafile: /cluster/projects/bhklab/projects/BCaATAC/BCa_ARCHE_Scoring/metadata/cfDNA_metadata.txt
consensusfile: /cluster/projects/bhklab/projects/BCaATAC/BCa_ARCHE_Scoring/data/results/cfDNA/consensus/PeakCalls_unionPeakSet.bed
PEAKS_DIR: /cluster/projects/bhklab/rawdata/BCaATAC/ATAC-cfDNA/narrowpeaks/
peaks_extension: "_peaks.filtered.merged.narrowPeak"
hg38TEs_DIR: /cluster/projects/bhklab/projects/BCaATAC/BCa_ARCHE_Scoring/data/procdata/ARCHEs/20k_sites/
hg38TEs_extension: ".bed"
RESULTS_DIR: "/cluster/projects/bhklab/projects/BCaATAC/BCa_ARCHE_Scoring/data/results/cfDNA/20k"
qval: 0.01